"""Federation to location

Revision ID: 125bf332668c
Revises: f5d5e227cd33
Create Date: 2025-07-21 15:03:04.596321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '125bf332668c'
down_revision: Union[str, Sequence[str], None] = 'f5d5e227cd33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournaments', sa.Column('location', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_column('tournaments', 'federation')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournaments', sa.Column('federation', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('tournaments', 'location')
    # ### end Alembic commands ###
