"""Modify tournament model

Revision ID: 26702e07b600
Revises: bb605d9ef646
Create Date: 2025-07-22 09:50:34.522084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '26702e07b600'
down_revision: Union[str, Sequence[str], None] = 'bb605d9ef646'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournaments', sa.Column('format', sa.Enum('ROUND_ROBIN', 'SWISS', 'ELIMINATION', 'DOUBLE_ELIMINATION', name='format', native_enum=False), server_default='Round-Robin', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tournaments', 'format')
    # ### end Alembic commands ###
