"""Add unique constraint

Revision ID: 437b16942a3b
Revises: fe5e0b392247
Create Date: 2025-07-23 21:41:16.332129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '437b16942a3b'
down_revision: Union[str, Sequence[str], None] = 'fe5e0b392247'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('_name_tournament_id_uc_', 'players', ['name', 'tournament_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_name_tournament_id_uc_', 'players', type_='unique')
    # ### end Alembic commands ###
