"""Add lichess_token to user model 2

Revision ID: 60ef2ce8dcb7
Revises: 8418464e78a8
Create Date: 2025-07-30 21:18:27.151245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '60ef2ce8dcb7'
down_revision: Union[str, Sequence[str], None] = '8418464e78a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'lichess_token',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'lichess_token',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
