"""Simplify player model

Revision ID: bb605d9ef646
Revises: 125bf332668c
Create Date: 2025-07-21 17:37:19.690175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'bb605d9ef646'
down_revision: Union[str, Sequence[str], None] = '125bf332668c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'country')
    op.drop_column('players', 'title')
    op.drop_column('players', 'age')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('players', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('players', sa.Column('country', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
