"""Tournament status

Revision ID: f5d5e227cd33
Revises: 855f592e156b
Create Date: 2025-07-21 11:03:55.795581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f5d5e227cd33'
down_revision: Union[str, Sequence[str], None] = '855f592e156b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournaments', sa.Column('status', sa.Enum('NOT_STARTED', 'ONGOING', 'FINISHED', name='status', native_enum=False), server_default='Not Started', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tournaments', 'status')
    # ### end Alembic commands ###
