"""Add rounds/matcups models

Revision ID: 214502953fbf
Revises: 26702e07b600
Create Date: 2025-07-22 11:14:13.324513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '214502953fbf'
down_revision: Union[str, Sequence[str], None] = '26702e07b600'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rounds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('matchups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('result', sa.Enum('WHITE_WINS', 'BLACK_WINS', 'DRAW', name='result', native_enum=False), server_default='Draw', nullable=True),
    sa.Column('round_id', sa.Integer(), nullable=False),
    sa.Column('white_player_id', sa.Integer(), nullable=False),
    sa.Column('black_player_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['black_player_id'], ['players.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['round_id'], ['rounds.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['white_player_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('matchups')
    op.drop_table('rounds')
    # ### end Alembic commands ###
