"""Add nb_of_players to tournaments

Revision ID: 9ada6171ee65
Revises: 214502953fbf
Create Date: 2025-07-22 13:49:54.671029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9ada6171ee65'
down_revision: Union[str, Sequence[str], None] = '214502953fbf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournaments', sa.Column('nb_of_players', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tournaments', 'nb_of_players')
    # ### end Alembic commands ###
